### ISSUE TITLE
`make -C qsys generatedtssrc` doesn't work on windows

### ISSUE THREAD

**Issue by amagid** [eradani-inc/ecc-template#19]
It is really close, but it tries to run the `system "CPYFRMSTMF..."` so it fails after processing the first YAML file.

I'm not sure if the `generatedtssrc` target matters for the usual build, so I haven't modified it. However, the purpose of the `generatedtssrc` target originally was so that we could use the makefile to generate all yaml on windows without npm scripts.

**Comment by amagid** [comment]
@dromonaco Is there a way we can get around this so that `make -C qsys generatedtssrc` can be used for building on non-IBM i without impacting the build on IBM i, where we typically do `make -C qsys`?

**Comment by dromonaco** [comment]
`make -C qsys generatedtssrc -i` will work
